### ISSUE TITLE
Editing a request and removing all availability

### ISSUE THREAD

**Issue by semidirect** [uchicago-cs/cs121-officehours-webapp#11]
If a student makes a request, and then goes back and edits the request and removes all availability, then they are taken back to the page to submit a request, except that now all time slots are shown as options, not just the time slots for today, and the Submit/Update button has no text in it and is small.

This other issue is also about submitting the request form with no time slots selected: https://github.com/uchicago-cs/cs121-officehours-webapp/issues/5#issue-526207714

**Comment by borjasotomayor** [comment]
I've pushed a fix for this, and have deployed it to staging: https://cs121-officehours-staging.herokuapp.com/ Please close this issue if you feel it has been resolved.
