### ISSUE TITLE
Make Quick Questions Easier to See

### ISSUE THREAD

**Issue by dwahme** [uchicago-cs/cs121-officehours-webapp#12]
In the "Pending Now" (I think) and "Pending Today" tabs, it's challenging to differentiate quick questions from regular questions. These should be easily identifiable so that they are guaranteed to be prioritized and so that unnecessary time isn't spent staring at a long list of requests.

Some possible solutions:
- Make quick questions have a green QUICK tag like the red PRIORITY tag
- Separate quick questions from regular questions
- Add some other visual indicator in the pending list such as coloring the request text or background

**Comment by borjasotomayor** [comment]
I've pushed a fix for this, and have deployed it to staging: https://cs121-officehours-staging.herokuapp.com/ Please close this issue if you feel it has been resolved.

**Comment by dwahme** [comment]
LGTM
