### ISSUE TITLE
Validation of Zoom URL

### ISSUE THREAD

**Issue by semidirect** [uchicago-cs/cs121-officehours-webapp#19]
It would be useful for the form to require the Zoom URL to begin with https://uchicago.zoom.us/

**Comment by borjasotomayor** [comment]
I've added some basic validation and deployed to staging. Right now, it only checks whether the URL starts with https://uchicago.zoom.us/, which is probably enough. We could do some fancier validation with regular expressions (to make sure it's specifically a meeting URL), but that means things could break if Zoom changes their URL format at any point.

**Comment by semidirect** [comment]
I don't think it's necessary to do validation beyond that; if someone really wants to send us an invalid link, they still can, but I don't expect that to be a problem, and this already prevents them from trying to send us links to other things, like non-Zoom calls.

**Comment by borjasotomayor** [comment]
Ok, in that case, I'm closing this issue.
