### ISSUE TITLE
Show students their own request description

### ISSUE THREAD

**Issue by semidirect** [uchicago-cs/cs121-officehours-webapp#4]
On the my-request page, we could display the description of the request that the student submitted, so that they can more easily notice when their issue changes and the description is no longer accurate, or notice that they could add more detail to their description.

**Comment by borjasotomayor** [comment]
I've pushed a fix for this, and have deployed it to staging: https://cs121-officehours-staging.herokuapp.com/ Please close this issue if you feel it has been resolved.
