### ISSUE TITLE
Keeping issue visible after clicking "Start Service"

### ISSUE THREAD

**Issue by semidirect** [uchicago-cs/cs121-officehours-webapp#8]
After clicking "Start Service" for an request on the "Scheduled" tab of the "Today's Requests" page, the request disappears. It would be useful to be able to continue to look at the request without more clicks. One way to accomplish this would be to automatically open the "In Progress" tab after clicking "Start Service," and have that request automatically expanded.

**Comment by borjasotomayor** [comment]
I've pushed a fix for this which makes sure that, after scheduling a request or starting/stopping service, the next tab show is the one for the request's new status (I haven't figured out a way to highlight that request, though).

I've deployed the fix to staging: https://cs121-officehours-staging.herokuapp.com/ Please close this issue if you feel it has been resolved.
